version: '3.9'

services:
  ganache:
    image: trufflesuite/ganache:v7.3.1
    ports: 
      - 8545:8545
    command: --mnemonic="gate man immense path adult develop color remove belt foot year future"
  frontend:
    volumes:
      - ./:/app
    build: ./Frontend/
    ports: 
      - 4200:4200
    depends_on:
      - ganache
